[global]

# If false, makes your Streamlit script shareable via st.share.streamlit.io
share = false

# Enables support for Arrow
dataFrameSerialization = "arrow"

[logger]

# Level of logging: 'error', 'warning', 'info', 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, will attempt to open a new tab or window every time Streamlit is
# called. If true, will only open a new tab the first time Streamlit is called.
showSidebarNavigation = true

# Controls whether uncaught app exceptions are displayed in the browser. By
# default, this is set to True and Streamlit displays app exceptions and
# associated tracebacks in the browser.
showErrorDetails = true

[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
folderWatchBlacklist = ['']

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# this should be set to the same value across all replicas to ensure they all
# share the same secret.
cookieSecret = "a-random-key-appears-here"

# If false, will attempt to open a new tab or window every time Streamlit is
# called. If true, will only open a new tab the first time Streamlit is called.
headless = true

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections.
address = "0.0.0.0"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for websocket connections and server support for multiple
# browser tabs connecting to the same Streamlit instance.
enableWebsocketCompression = false

[browser]

# Internet address where users should point their browsers in order to connect to
# the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the app.
serverPort = 8501
